export { default as IconLinkedIn } from './about/IconLinkedIn.vue'
export { default as IconResume } from './about/IconResume.vue'
export { default as IconContact } from './about/IconContact.vue'
export { default as IconEducation } from './about/IconEducation.vue'
export { default as IconExperience } from './about/IconExperience.vue'
export { default as IconProject } from './about/IconProject.vue'

export { default as IconPublishing } from './skills/IconPublishing.vue'
export { default as IconFront } from './skills/IconFront.vue'
export { default as IconBack } from './skills/IconBack.vue'
export { default as IconDatabase } from './skills/IconDatabase.vue'
export { default as IconEcommerce } from './skills/IconEcommerce.vue'
export { default as IconHybrid } from './skills/IconHybrid.vue'
export { default as IconCommunication } from './skills/IconCommunication.vue'
export { default as IconGitlab } from './skills/IconGitlab.vue'

export { default as IconHtml } from './project/IconHtml.vue'
export { default as IconCss } from './project/IconCss.vue'
export { default as IconJs } from './project/IconJs.vue'
export { default as IconResponsive } from './project/IconResponsive.vue'
export { default as IconVue } from './project/IconVue.vue'

export { default as IconDuration } from './project/IconDuration.vue'
export { default as IconTechnology } from './project/IconTechnology.vue'
export { default as IconRole } from './project/IconRole.vue'
export { default as IconGallery } from './project/IconGallery.vue'

export { default as IconArrowType1 } from './common/IconArrowType1.vue'
export { default as IconXmark } from './common/IconXmark.vue'
