export { default as IconLinkedIn } from './about/IconLinkedIn.vue'
export { default as IconResume } from './about/IconResume.vue'
export { default as IconContact } from './about/IconContact.vue'
export { default as IconEducation } from './about/IconEducation.vue'
export { default as IconExperience } from './about/IconExperience.vue'
export { default as IconProject } from './about/IconProject.vue'
